### PR TITLE
Jimdelois bugfix/issue 93

### LINKED ISSUE #93: Unable to Differentiate Between Bad Paths and Bad Methods on Good Paths
Given something like the following (the rethrown exceptions are part of the local framework):
```
        try {
            $this->requestValidator->validate($request);
        } catch (Exception\NoOperation $e) {
            throw new HttpException\HttpMethodNotAllowedException($request, 'Method Not Allowed', $e);
        } catch (Exception\NoPath $e) {
            throw new HttpException\HttpNotFoundException($request, 'Not Found', $e);
        }
```
... It seems that whatever I catch first catches everything.  That is to say, a bad path on the case above yields a `405` (unexpected), as does a bad method (expected).  If I reverse the two catches, the opposite occurs...  A bad path on the case yields a `404` (expected) and a bad method yields a `405` (unexpected).

The only way that's possible, based on one exception extending the other, is if the `NoOperation` is the only thing thrown in all cases.

From your own doc:
```
\League\OpenAPIValidation\PSR7\Exception\NoPath - path is not found in the spec
\League\OpenAPIValidation\PSR7\Exception\NoOperation - operation os not found in the path
```
I have not yet dug into the internals, but the documentation very strongly suggests that these are different outcomes, which would be in alignment with the HTTP spec.  Evidently they are not.

It seems a pretty significant issue that one cannot differentiate something that should be bubbled as a `404` vs. a `405`.  There also seems to be something that isn't working with the `NoContentType` that I can't possible trigger in tests.

Can someone educate me on how to work with these different exceptions such that I can appropriately recast them up to the client?  Is it merely a documentation issue that I'm not seeing?  If I've overlooked something, can anyone provide some input?

Any assistance is much appreciated!!  I'm assuming there's a shortcoming with myself, but if there's actually something to be improved within the library then perhaps I could eventually attempt to patch it.

### PR DESCRIPTION
**Pull request by scaytrase**
Dirty fix for #93. I think it's decreases performance, so we need to find better way to handle that, but just to start discussion

Fixes #93  

cc. @jimdelois

### CODE REVIEW

File: src/PSR7/RequestValidator.php [hunk 1]
```diff
@@ -102,4 +107,14 @@ private function findMatchingOperations(RequestInterface $request) : array
...
     }
+
+    /**
+     * Checks whether request matches any path in schema
+     */
+    private function hasMatchingPaths(RequestInterface $request) : bool
+    {
+        $pathFinder = new PathFinder($this->openApi, (string) $request->getUri(), $request->getMethod());
+
+        return $pathFinder->getPathMatches() !== [];
```
Comment (scaytrase) [inline src/PSR7/RequestValidator.php:118]: Actually I think we can make it as fast caching data in `PathFinder` (it's statefyl at the moment, so we can do that easily). For this we need to.  Use same `PathFinder` twice

**Review by jimdelois — APPROVED** [review]
LGTM - thanks!
